### ISSUE TITLE
管理后台绑定编辑无效

### ISSUE THREAD

**Issue by zenonux** [doramart/DoraCMS-SQL#1]
targetEditor始终为空[详细图片1](https://photo.urcloud.co/uploads/big/9de9d4e1c1d608a99371d98077890100.png)[图片2](https://photo.urcloud.co/uploads/big/4eb9e0656a5e774d9e4dd4b7991cd227.png)

**Comment by doramart** [comment]
重新导入 doracms.sql,并更新代码

**Comment by zenonux** [comment]
> 重新导入 doracms.sql,并更新代码

可以了，谢谢生哥
