### ISSUE TITLE
后台系统公告面板界面样式错误

### ISSUE THREAD

**Issue by zenonux** [doramart/DoraCMS-SQL#10]
#announce-app .main-container 的margin-left 不对
![image](https://user-images.githubusercontent.com/8474239/99610671-37af0f00-2a4d-11eb-8653-da42628e1133.png)

**Comment by doramart** [comment]
可否具体点，没看明白是哪里的问题，谢谢！

**Comment by zenonux** [comment]
![image](https://user-images.githubusercontent.com/8474239/99903362-dca44300-2cfe-11eb-8708-cd53b2e13dd6.png)
#announce-app .main-container 的margin-left 应该为210px，现在是0，导致添加系统公告的按钮被隐藏

**Comment by doramart** [comment]
https://github.com/doramart/DoraCMS-SQL/commit/d132217b0bab3600d35f3c289bbb85ab52ef7bc7

**Comment by zenonux** [comment]
> [d132217](https://github.com/doramart/DoraCMS-SQL/commit/d132217b0bab3600d35f3c289bbb85ab52ef7bc7)

哈哈 刚刚提了个request

**Comment by doramart** [comment]
谢谢贡献代码，没注意
