### ISSUE TITLE
后台用户管理报错

### ISSUE THREAD

**Issue by superzhy** [doramart/DoraCMS-SQL#19]
![image](https://user-images.githubusercontent.com/34673392/111742798-adc06700-88c3-11eb-87b6-ad55de2db4c9.png)

用户管理进入报错

**Comment by 992185100** [comment]
删了dist 目录下面的 adminUser 目录， 并重新打包后，还是报错，不知道楼上的怎么解决的？求赐教

**Comment by doramart** [comment]
更新最新的代码再试一次，另外把chrome的广告插件暂时关掉
