### ISSUE TITLE
修改管理员用户信息报错

### ISSUE THREAD

**Issue by zenonux** [doramart/DoraCMS-SQL#2]
`Incorrect integer value: '[object Object]' for column 'group_id' at row 1`尝试在后台修改管理员姓名时报错。mysql8.0.17以及5.6均有问题

**Comment by doramart** [comment]
重新选择角色后保存

**Comment by doramart** [comment]
更新最新代码后重试

**Comment by zenonux** [comment]
> 更新最新代码后重试

可以了哈
