### ISSUE TITLE
希望增加一个在线客服功能 菜鸡建议？

### ISSUE THREAD

**Issue by APPX-Studio** [doramart/DoraCMS-SQL#20]
https://github.com/erxes/erxes
类似这种 开源
![image](https://user-images.githubusercontent.com/49307767/113371223-6d1f1e00-9398-11eb-9d37-e76c615fc4f5.png)

手机app 不是很好用 国内收不到消息。所以没法用。

**Comment by doramart** [comment]
定制功能自己根据需要自行添加
