### ISSUE TITLE
后台adminUser模块重新打包到backstage/dist/adminUser后报错

### ISSUE THREAD

**Issue by 992185100** [doramart/DoraCMS-SQL#22]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
system.min.js:4 GET http://localhost:7899/app.js net::ERR_CONNECTION_REFUSED
(anonymous) @ system.min.js:4
h.instantiate @ system.min.js:4
h.instantiate @ system.min.js:4
t.instantiate @ named-register.min.js:1
(anonymous) @ system.min.js:4
Promise.then (async)
t @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
h.import @ system.min.js:4
e.import @ system.min.js:4
t.import @ use-default.min.js:1
(anonymous) @ adminUser:146
(anonymous) @ load.js:18
Promise.then (async)
(anonymous) @ load.js:17
Promise.then (async)
tt @ load.js:8
(anonymous) @ reroute.js:40
Promise.then (async)
Ct @ reroute.js:39
Tt @ apps.js:73
(anonymous) @ adminUser:132
Promise.then (async)
(anonymous) @ adminUser:114
(anonymous) @ adminUser:161
app-errors.js:9 Uncaught adminUser: Application 'adminUser' died in status LOADING_SOURCE_CODE: Error loading http://localhost:7899/app.js
    at HTMLScriptElement.<anonymous> (http://127.0.0.1:10003/static/plugins/systemjs/4.1.0/system.min.js:4:4496)

**Comment by doramart** [comment]
config.local.js 里把  adminUser 模块注释掉
