### ISSUE TITLE
添加模版单元为空

### ISSUE THREAD

**Issue by zenonux** [doramart/DoraCMS-SQL#5]
添加模版单元为空，无法选择。使用的默认hidora主题，api数据有返回，前端无展示

**Comment by doramart** [comment]
请描述清晰，方便的话请截图

**Comment by zenonux** [comment]
> 请描述清晰，方便的话请截图

 [详细图片](https://photo.urcloud.co/uploads/big/cab67063505431d85e8353675bdc4358.png)

**Comment by doramart** [comment]
你是把模板卸载后重装的吗

**Comment by zenonux** [comment]
> 你是把模板卸载后重装的吗

这个不太能确定啊，期间有导入卸载切换模版，默认hidora的主题好像没有卸过

**Comment by doramart** [comment]
把 view 目录下 hidora 的目录截图看看，感觉少了东西

**Comment by zenonux** [comment]
> 把 view 目录下 hidora 的目录截图看看，感觉少了东西

 目录不缺，是bug，复现方法，dev开发环境，导入tempdemo主题（模版为空），切换至hidora主题（应该为2个模版），实际出现0，是因为切换主题之后没有刷新manage/template/getTemplateItemlist接口，刷新页面可以看到正常了

**Comment by doramart** [comment]
你的意思是切换时没有刷新接口引起的是吧？

**Comment by zenonux** [comment]
> 你的意思是切换时没有刷新接口引起的是吧？

是的

**Comment by doramart** [comment]
看了下，切换模板是有刷新的，但是SQL版本提供的导入模板可能有问题，可以尝试重新下载demo导入，然后切换试试
