### ISSUE TITLE
404模版没有渲染

### ISSUE THREAD

**Issue by zenonux** [doramart/DoraCMS-SQL#6]
`TypeError: Cannot destructure property 'title' of 'ctx.params' as it is undefined.`[测试地址](https://sql.html-js.cn/404)

**Comment by doramart** [comment]
404 是这么用的： https://sql.html-js.cn/details/700.html

**Comment by zenonux** [comment]
> 404 是这么用的： https://sql.html-js.cn/details/700.html

这样不太合理吧，找不到的路由就应该重定向到404吧

**Comment by doramart** [comment]
https://github.com/doramart/DoraCMS-SQL/commit/02cb4954bc03367014a4665654cb6782ff6ce103 更新代码后再试
