### ISSUE TITLE
广告模块没法使用

### ISSUE THREAD

**Issue by jakehu** [doramart/DoraCMS-SQL#8]
Uncaught ads: Application 'ads' died in status LOADING_SOURCE_CODE: Error loading https://cdn.html-js.cn/cms/plugins/static/sadmin/ads/js/app.js

**Comment by doramart** [comment]
麻烦截图看看具体的报错，先更新代码再试试

**Comment by jakehu** [comment]
没有看到后端报错，上面就是前端报错
演示环境也是一样的哟
https://sql.html-js.cn/admin/ads  这个地址

**Comment by hlwen** [comment]
可能是广告拦截插件拦截了，检查一下广告插件
![image](https://user-images.githubusercontent.com/13469676/99495836-367ad500-29ae-11eb-8426-6cbb1fa76ba6.png)

**Comment by jakehu** [comment]
居然真的是 @hlwen
